# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/projects/cpp/Uds_Simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/projects/cpp/Uds_Simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/cpp/Uds_Simulator/CMakeFiles /home/pi/projects/cpp/Uds_Simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projects/cpp/Uds_Simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UDS_Interacive

# Build rule for target.
UDS_Interacive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UDS_Interacive
.PHONY : UDS_Interacive

# fast build rule for target.
UDS_Interacive/fast:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/build
.PHONY : UDS_Interacive/fast

spike/InteractiveMain.o: spike/InteractiveMain.cpp.o

.PHONY : spike/InteractiveMain.o

# target to build an object file
spike/InteractiveMain.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/spike/InteractiveMain.cpp.o
.PHONY : spike/InteractiveMain.cpp.o

spike/InteractiveMain.i: spike/InteractiveMain.cpp.i

.PHONY : spike/InteractiveMain.i

# target to preprocess a source file
spike/InteractiveMain.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/spike/InteractiveMain.cpp.i
.PHONY : spike/InteractiveMain.cpp.i

spike/InteractiveMain.s: spike/InteractiveMain.cpp.s

.PHONY : spike/InteractiveMain.s

# target to generate assembly for a file
spike/InteractiveMain.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/spike/InteractiveMain.cpp.s
.PHONY : spike/InteractiveMain.cpp.s

src/Uds/Services/BaseService.o: src/Uds/Services/BaseService.cpp.o

.PHONY : src/Uds/Services/BaseService.o

# target to build an object file
src/Uds/Services/BaseService.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/BaseService.cpp.o
.PHONY : src/Uds/Services/BaseService.cpp.o

src/Uds/Services/BaseService.i: src/Uds/Services/BaseService.cpp.i

.PHONY : src/Uds/Services/BaseService.i

# target to preprocess a source file
src/Uds/Services/BaseService.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/BaseService.cpp.i
.PHONY : src/Uds/Services/BaseService.cpp.i

src/Uds/Services/BaseService.s: src/Uds/Services/BaseService.cpp.s

.PHONY : src/Uds/Services/BaseService.s

# target to generate assembly for a file
src/Uds/Services/BaseService.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/BaseService.cpp.s
.PHONY : src/Uds/Services/BaseService.cpp.s

src/Uds/Services/Service10.o: src/Uds/Services/Service10.cpp.o

.PHONY : src/Uds/Services/Service10.o

# target to build an object file
src/Uds/Services/Service10.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service10.cpp.o
.PHONY : src/Uds/Services/Service10.cpp.o

src/Uds/Services/Service10.i: src/Uds/Services/Service10.cpp.i

.PHONY : src/Uds/Services/Service10.i

# target to preprocess a source file
src/Uds/Services/Service10.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service10.cpp.i
.PHONY : src/Uds/Services/Service10.cpp.i

src/Uds/Services/Service10.s: src/Uds/Services/Service10.cpp.s

.PHONY : src/Uds/Services/Service10.s

# target to generate assembly for a file
src/Uds/Services/Service10.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service10.cpp.s
.PHONY : src/Uds/Services/Service10.cpp.s

src/Uds/Services/Service3E.o: src/Uds/Services/Service3E.cpp.o

.PHONY : src/Uds/Services/Service3E.o

# target to build an object file
src/Uds/Services/Service3E.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service3E.cpp.o
.PHONY : src/Uds/Services/Service3E.cpp.o

src/Uds/Services/Service3E.i: src/Uds/Services/Service3E.cpp.i

.PHONY : src/Uds/Services/Service3E.i

# target to preprocess a source file
src/Uds/Services/Service3E.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service3E.cpp.i
.PHONY : src/Uds/Services/Service3E.cpp.i

src/Uds/Services/Service3E.s: src/Uds/Services/Service3E.cpp.s

.PHONY : src/Uds/Services/Service3E.s

# target to generate assembly for a file
src/Uds/Services/Service3E.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Services/Service3E.cpp.s
.PHONY : src/Uds/Services/Service3E.cpp.s

src/Uds/Uds.o: src/Uds/Uds.cpp.o

.PHONY : src/Uds/Uds.o

# target to build an object file
src/Uds/Uds.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Uds.cpp.o
.PHONY : src/Uds/Uds.cpp.o

src/Uds/Uds.i: src/Uds/Uds.cpp.i

.PHONY : src/Uds/Uds.i

# target to preprocess a source file
src/Uds/Uds.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Uds.cpp.i
.PHONY : src/Uds/Uds.cpp.i

src/Uds/Uds.s: src/Uds/Uds.cpp.s

.PHONY : src/Uds/Uds.s

# target to generate assembly for a file
src/Uds/Uds.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Uds.cpp.s
.PHONY : src/Uds/Uds.cpp.s

src/Uds/Utility/Convert.o: src/Uds/Utility/Convert.cpp.o

.PHONY : src/Uds/Utility/Convert.o

# target to build an object file
src/Uds/Utility/Convert.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Convert.cpp.o
.PHONY : src/Uds/Utility/Convert.cpp.o

src/Uds/Utility/Convert.i: src/Uds/Utility/Convert.cpp.i

.PHONY : src/Uds/Utility/Convert.i

# target to preprocess a source file
src/Uds/Utility/Convert.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Convert.cpp.i
.PHONY : src/Uds/Utility/Convert.cpp.i

src/Uds/Utility/Convert.s: src/Uds/Utility/Convert.cpp.s

.PHONY : src/Uds/Utility/Convert.s

# target to generate assembly for a file
src/Uds/Utility/Convert.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Convert.cpp.s
.PHONY : src/Uds/Utility/Convert.cpp.s

src/Uds/Utility/Request.o: src/Uds/Utility/Request.cpp.o

.PHONY : src/Uds/Utility/Request.o

# target to build an object file
src/Uds/Utility/Request.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Request.cpp.o
.PHONY : src/Uds/Utility/Request.cpp.o

src/Uds/Utility/Request.i: src/Uds/Utility/Request.cpp.i

.PHONY : src/Uds/Utility/Request.i

# target to preprocess a source file
src/Uds/Utility/Request.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Request.cpp.i
.PHONY : src/Uds/Utility/Request.cpp.i

src/Uds/Utility/Request.s: src/Uds/Utility/Request.cpp.s

.PHONY : src/Uds/Utility/Request.s

# target to generate assembly for a file
src/Uds/Utility/Request.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Request.cpp.s
.PHONY : src/Uds/Utility/Request.cpp.s

src/Uds/Utility/Response.o: src/Uds/Utility/Response.cpp.o

.PHONY : src/Uds/Utility/Response.o

# target to build an object file
src/Uds/Utility/Response.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Response.cpp.o
.PHONY : src/Uds/Utility/Response.cpp.o

src/Uds/Utility/Response.i: src/Uds/Utility/Response.cpp.i

.PHONY : src/Uds/Utility/Response.i

# target to preprocess a source file
src/Uds/Utility/Response.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Response.cpp.i
.PHONY : src/Uds/Utility/Response.cpp.i

src/Uds/Utility/Response.s: src/Uds/Utility/Response.cpp.s

.PHONY : src/Uds/Utility/Response.s

# target to generate assembly for a file
src/Uds/Utility/Response.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Uds/Utility/Response.cpp.s
.PHONY : src/Uds/Utility/Response.cpp.s

src/Vehicle/BaseVehicle.o: src/Vehicle/BaseVehicle.cpp.o

.PHONY : src/Vehicle/BaseVehicle.o

# target to build an object file
src/Vehicle/BaseVehicle.cpp.o:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Vehicle/BaseVehicle.cpp.o
.PHONY : src/Vehicle/BaseVehicle.cpp.o

src/Vehicle/BaseVehicle.i: src/Vehicle/BaseVehicle.cpp.i

.PHONY : src/Vehicle/BaseVehicle.i

# target to preprocess a source file
src/Vehicle/BaseVehicle.cpp.i:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Vehicle/BaseVehicle.cpp.i
.PHONY : src/Vehicle/BaseVehicle.cpp.i

src/Vehicle/BaseVehicle.s: src/Vehicle/BaseVehicle.cpp.s

.PHONY : src/Vehicle/BaseVehicle.s

# target to generate assembly for a file
src/Vehicle/BaseVehicle.cpp.s:
	$(MAKE) -f CMakeFiles/UDS_Interacive.dir/build.make CMakeFiles/UDS_Interacive.dir/src/Vehicle/BaseVehicle.cpp.s
.PHONY : src/Vehicle/BaseVehicle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... UDS_Interacive"
	@echo "... edit_cache"
	@echo "... spike/InteractiveMain.o"
	@echo "... spike/InteractiveMain.i"
	@echo "... spike/InteractiveMain.s"
	@echo "... src/Uds/Services/BaseService.o"
	@echo "... src/Uds/Services/BaseService.i"
	@echo "... src/Uds/Services/BaseService.s"
	@echo "... src/Uds/Services/Service10.o"
	@echo "... src/Uds/Services/Service10.i"
	@echo "... src/Uds/Services/Service10.s"
	@echo "... src/Uds/Services/Service3E.o"
	@echo "... src/Uds/Services/Service3E.i"
	@echo "... src/Uds/Services/Service3E.s"
	@echo "... src/Uds/Uds.o"
	@echo "... src/Uds/Uds.i"
	@echo "... src/Uds/Uds.s"
	@echo "... src/Uds/Utility/Convert.o"
	@echo "... src/Uds/Utility/Convert.i"
	@echo "... src/Uds/Utility/Convert.s"
	@echo "... src/Uds/Utility/Request.o"
	@echo "... src/Uds/Utility/Request.i"
	@echo "... src/Uds/Utility/Request.s"
	@echo "... src/Uds/Utility/Response.o"
	@echo "... src/Uds/Utility/Response.i"
	@echo "... src/Uds/Utility/Response.s"
	@echo "... src/Vehicle/BaseVehicle.o"
	@echo "... src/Vehicle/BaseVehicle.i"
	@echo "... src/Vehicle/BaseVehicle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

